Repository giagor/PureJoy, pull requests merged in 2022-03, with the labels that each got.

#224 Adjust download thread nums
  common/src/main/java/com/topview/purejoy/common/component/download/configure/DefaultDownloadConfiguration.kt
Labels: enhancement

#226 Common - Fix - Fix application crash caused by music process death
  common/src/main/java/com/topview/purejoy/common/music/player/client/BinderPoolClient.kt
  common/src/main/java/com/topview/purejoy/common/music/view/bottom/MusicController.kt
Labels: bug

#228 Modify some configurations in download library
  common/src/main/java/com/topview/purejoy/common/component/download/DownloadManager.kt
  common/src/main/java/com/topview/purejoy/common/component/download/configure/DefaultDownloadConfiguration.kt
  common/src/main/java/com/topview/purejoy/common/component/download/configure/DownloadConfiguration.kt
  common/src/main/java/com/topview/purejoy/common/component/download/dispatcher/DownloadDispatcher.kt
  common/src/main/java/com/topview/purejoy/common/component/download/util/Constant.kt
Labels: enhancement

#230 Provide a common interface to load image
  common/src/main/java/com/topview/purejoy/common/component/image/ImageLoader.kt
  common/src/main/java/com/topview/purejoy/common/component/image/ImageUtil.kt
  common/src/main/java/com/topview/purejoy/common/component/image/impl/GlideImageLoader.kt
  common/src/main/java/com/topview/purejoy/common/mvvm/binding/CommonBindingAdapters.kt
  home/src/main/java/com/topview/purejoy/home/entity/HomeDiscoverBannerItem.kt
Labels: enhancement

#234 Common - Fix - Fix some bug
  common/src/main/java/com/topview/purejoy/common/music/player/impl/controller/MediaControllerImpl.kt
  common/src/main/java/com/topview/purejoy/common/music/player/service/MediaService.kt
  common/src/main/java/com/topview/purejoy/common/music/service/MusicService.kt
Labels: bug

#236 Add return value for download API
  common/src/main/java/com/topview/purejoy/common/component/download/task/DownloadTask.kt
Labels: feature
