Repository giagor/PureJoy, pull requests merged in 2022-02, with the labels that each got.

#193 Add readme
  README.md
  screenshots/discover.jpg
  screenshots/download_manage.jpg
  screenshots/play_detail.jpg
  screenshots/playlist_list.jpg
  screenshots/video_list.jpg
  screenshots/video_play.jpg
Labels: documentation

#195 Home - Feature - Add clear cache
  common/src/main/java/com/topview/purejoy/common/util/FileUtil.kt
  home/src/main/java/com/topview/purejoy/home/mine/HomeMineFragment.kt
  home/src/main/res/layout/fragment_home_mine.xml
  home/src/main/res/layout/simple_dialog.xml
  home/src/main/res/values/strings.xml
Labels: feature

#196 Fix some bugs and refactor login screen
  common/src/main/java/com/topview/purejoy/common/widget/compose/RoundedCornerImageView.kt
  home/src/main/java/com/topview/purejoy/home/components/login/LoginLoadState.kt
  home/src/main/java/com/topview/purejoy/home/components/login/PasswordLoginScreen.kt
  home/src/main/java/com/topview/purejoy/home/components/login/PhoneScreen.kt
  home/src/main/java/com/topview/purejoy/home/components/status/PageState.kt
  home/src/main/java/com/topview/purejoy/home/components/status/SnackBarEvent.kt
  home/src/main/java/com/topview/purejoy/home/components/status/SnackBarState.kt
  home/src/main/java/com/topview/purejoy/home/data/api/LoginService.kt
  home/src/main/java/com/topview/purejoy/home/data/source/LoginRemoteStore.kt
  home/src/main/java/com/topview/purejoy/home/tasks/about/AboutActivity.kt
  home/src/main/java/com/topview/purejoy/home/tasks/login/CaptchaFragment.kt
  home/src/main/java/com/topview/purejoy/home/tasks/login/CaptchaViewModel.kt
  home/src/main/java/com/topview/purejoy/home/tasks/login/LoginViewModel.kt
  home/src/main/java/com/topview/purejoy/home/tasks/login/PasswordFragment.kt
  home/src/main/java/com/topview/purejoy/home/tasks/login/PasswordViewModel.kt
  home/src/main/java/com/topview/purejoy/home/tasks/login/PhoneInputFragment.kt
Labels: bug

#198 Home - Enhance - Optimize code
  home/src/main/java/com/topview/purejoy/home/mine/HomeMineFragment.kt
  home/src/main/java/com/topview/purejoy/home/mine/HomeMineViewModel.kt
Labels: enhancement

#200 Dynamically adjust download thread count in download library
  common/src/main/AndroidManifest.xml
  common/src/main/java/com/topview/purejoy/common/app/CommonApplication.kt
  common/src/main/java/com/topview/purejoy/common/component/download/DownloadManager.kt
  common/src/main/java/com/topview/purejoy/common/component/download/configure/DefaultDownloadConfiguration.kt
  common/src/main/java/com/topview/purejoy/common/component/download/task/handler/TaskHandler.kt
  common/src/main/java/com/topview/purejoy/common/component/download/util/ContextProvider.kt
Labels: enhancement

#203 Exception loading pictures after clearing coil file cache
  common/.gitignore
  common/build.gradle.kts
  common/src/main/java/com/topview/purejoy/common/util/FileUtil.kt
  home/src/main/java/com/topview/purejoy/home/mine/HomeMineViewModel.kt
Labels: bug

#205 Make common suspend function support cancellation
  common/src/main/java/com/topview/purejoy/common/net/Await.kt
Labels: enhancement

#207 Use awaitAsync when net request
  home/src/main/java/com/topview/purejoy/home/data/repo/HomeRepository.kt
  home/src/main/java/com/topview/purejoy/home/data/source/HomeRemoteStore.kt
Labels: enhancement

#211 Add cancel call in awaitAsync
  common/src/main/java/com/topview/purejoy/common/net/Await.kt
Labels: enhancement

#213 refactor: replace deprecated function awaitSync with awaitAsync
  common/src/main/java/com/topview/purejoy/common/net/Await.kt
  home/src/main/java/com/topview/purejoy/home/data/repo/HomeVideoRepository.kt
  home/src/main/java/com/topview/purejoy/home/data/repo/LoginRepository.kt
  home/src/main/java/com/topview/purejoy/home/data/repo/TopListRepository.kt
  home/src/main/java/com/topview/purejoy/home/data/source/CategorySource.kt
  home/src/main/java/com/topview/purejoy/home/data/source/LoginRemoteStore.kt
  home/src/main/java/com/topview/purejoy/home/data/source/TopListRemoteStore.kt
  video/src/main/java/com/topview/purejoy/video/data/VideoSource.kt
  video/src/main/java/com/topview/purejoy/video/data/repo/VideoRepository.kt
Labels: refactor

#222 Don't expose immutable LiveData outside
  common/src/main/java/com/topview/purejoy/common/business/download/manage/DownloadManageViewModel.kt
  home/src/main/java/com/topview/purejoy/home/discover/HomeDiscoverViewModel.kt
  home/src/main/java/com/topview/purejoy/home/search/content/playlist/SearchContentPlayListViewModel.kt
  home/src/main/java/com/topview/purejoy/home/search/content/song/SearchContentSongViewModel.kt
Labels: enhancement
